using Microsoft.EntityFrameworkCore.Migrations;

namespace SchoolManagementSystem.Migrations
{
    public partial class ModifyCourseModel : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "AutoGeneratedNumberOfClassesNeeded",
                table: "Courses",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "NumberOfClassesNeededToCompleteCourse",
                table: "Courses",
                nullable: false,
                defaultValue: 0);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AutoGeneratedNumberOfClassesNeeded",
                table: "Courses");

            migrationBuilder.DropColumn(
                name: "NumberOfClassesNeededToCompleteCourse",
                table: "Courses");
        }
    }
}
